// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsjgvmceqchinpbbtius.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzamd2bWNlcWNoaW5wYmJ0aXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjM5MjksImV4cCI6MjA3Mzc5OTkyOX0.Ioq9rUDuD_z5syKut9TZU-8PiaAN2Im1OJ6kqPWEVu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});